apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: docker.io/myarosh/lab:1.0.0
          ports:
            - name: port1
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /hello.html
              port: port1
            initialDelaySeconds: 5
            periodSeconds: 5
